#!/usr/bin/env bash
# vim: set filetype=sh:
#
# Usage:
#
#   ./ipe [ ... TODO ... ]
#
# Based on a template by BASH3 Boilerplate v2.0.0
# Copyright (c) 2016 Xavier Bruhiere and contributors

# Exit on error. Append || true if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail
# Turn on traces, useful while debugging but commented out by default
# set -o xtrace

# constants (
  # Set magic variables for current file, directory, os, etc.
  # __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  # __file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
  # __base="$(basename ${__file} .sh)"

  PROGRAM="${0##*/}"
  IPE_VERSION="0.1.0"
  IPE_HOME=$HOME/.ipe
  IPE_LIB=${IPE_HOME}/lib
  IPE_PKG=${IPE_HOME}/pkg
  # USER_SHELLRC=$HOME/.$(basename $SHELL)rc
  FNAME_CHARS='[a-zA-Z0-9_-]'
# )

_ipe_log() {
  echo "[ ipe ] $@"
}

cmd_version() {
  echo -e "ζ ipe v${IPE_VERSION} - Insanely Productive Environment\n"
}

cmd_usage() {
  cmd_version
  cat <<_EOF
Usage:

  $PROGRAM
    Print version and this helpful message

  $PROGRAM install <package_url>
    Download and make an ipe library available for loading.

  $PROGRAM (.|hack) <project>
    Activate <project> environment.

  $PROGRAM (env|what)
    Show environment description and available commands

  $PROGRAM reset
    Remove packages and dependencies.
_EOF
}

_reload_lib() {
  . "${IPE_HOME}/{lib,pkg}/*.sh"
}

cmd_work() {
  local project=${1}

  _ipe_log "activating '${project}' environment"
  . "${IPE_LIB}/z.sh"
  _z 2>&1 "${project}"

  # drop us in the script current shell
  # http://stackoverflow.com/questions/255414/why-doesnt-cd-work-in-a-bash-shell-script
  exec "$SHELL"
}

# Echo a list of aliases, exports, and functions for a given desk
get_callables() {
      local env_file=${1:-"./.env"}

      #grep -E "^(alias |export |(function )?${FNAME_CHARS}+ ?\()|function $NAME" "${env_file}" \
      cat "${env_file}" | grep -A1 "##" \
        | sed 's/alias \([^= ]*\)=.*/\1/' \
        | sed 's/export \([^= ]*\)=.*/\1/' \
        | sed -E "s/(function )?(${FNAME_CHARS}+) ?\(\).*/\2/" \
        | sed -E "s/function (${FNAME_CHARS}+).*/\1/"
}

require() {
  local package_url="$1"
  local package_name="$(basename ${package_url})"

  if [[ ! -f "${IPE_PKG}/${package_name}" ]]; then
    _ipe_log "downloading ${package_name}..."
    wget -q --directory-prefix ${IPE_PKG} ${package_url}
  fi

  _ipe_log "loading ${package_name}"
  . ${IPE_PKG}/${package_name}
}

cmd_reset() {
  rm -rf ${IPE_HOME}
}

case "${1:-}" in
  help|-h|--help) shift;        cmd_usage "$@" ;;
  version|-v|--version) shift;  cmd_version "$@" ;;
  hack|.) shift;                cmd_work "$@" ;;
  install) shift;               require "$@" ;;
  env|what) shift;              get_callables "$@" ;;
  reset) shift;                 cmd_reset "$@" ;;
  *)                            cmd_usage "$@" ;;
esac
exit 0
